<?php

namespace Adauga\faniBundle\Repository;

/**
 * FaniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaniRepository extends \Doctrine\ORM\EntityRepository
{
}
