<?php
// src/Blogger/BlogBundle/Repository/ContactRepository.php
namespace Blogger\BlogBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
*/
class ContactRepository extends EntityRepository
{
	public function getLatestContacts($limit = null)
	{
		$qb = $this->getEntityManager()->createQueryBuilder()
		->select('b')->from($this->getEntityName(), "b")
		->addOrderBy('b.created', 'DESC');
		if (false === is_null($limit))
		{
			$qb->setMaxResults($limit);
		}
		
		$query = $qb->getQuery();
		
		return $query->getResult();
	}
	
}